/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/

// @ts-nocheck
export default {
  'home':["/", "default", () => import('../src/base/page/home')],
}
