#!/usr/bin/env node

if (
  !process.argv.includes("pre-commit") &&
  !process.argv.includes("post-commit")
) {
  console.log(`
▄▄▄         ▄· ▄▌ ▄▄▄· ▄▄▌
▀▄ █·▪     ▐█▪██▌▐█ ▀█ ██•
▐▀▀▄  ▄█▀▄ ▐█▌▐█▪▄█▀▀█ ██▪
▐█•█▌▐█▌.▐▌ ▐█▀·.▐█ ▪▐▌▐█▌▐▌
.▀  ▀ ▀█▄▀▪  ▀ •  ▀  ▀ .▀▀▀
`);
}

const { spawn, spawnSync } = require("child_process");
const { existsSync } = require("fs");
const { join } = require("path");

(async () => {
  if (!existsSync(join(process.cwd(), "node_modules"))) {
    await new Promise((resolve) => {
      const pnpm = spawn("pnpm", ["i"], { stdio: "inherit", shell: true });
      pnpm.on("exit", resolve);
    });
  }

  const basePath = join(process.cwd(), ".output", ".cache", "base", "main.js");

  const args = process.argv.slice(2);
  while (true) {
    let base = null;
    if (existsSync(basePath)) {
      base = spawn(
        process.execPath,
        ["--enable-source-maps", basePath, ...args],
        {
          cwd: process.cwd(),
          stdio: "inherit",
        }
      );
    }

    spawnSync(
      "node",
      ["-r", "@swc-node/register", "pkgs/base/src/build-main.ts", ...args],
      {
        stdio: "inherit",
      }
    );

    if (!!base) {
      await new Promise((resolve) => {
        base.onExit(resolve);
      });
    }
  }
})();
