import { dirname, join } from "path";
import {
  dirAsync,
  findAsync,
  listAsync,
  readAsync,
  removeAsync,
  writeAsync,
} from "service";

import { parse, traverse } from "@babel/core";
import pluginTs from "@babel/plugin-syntax-typescript";
import { stat } from "fs/promises";
import { ApiMetaParams } from "service";

export const scaffoldAPI = async (name: string, path: string) => {
  await dirAsync(path);
  const index = [] as { name: string; path: string }[];

  let _url: Record<string, string> = {};
  let _params: ApiMetaParams = {};
  const root = join(dirname(path), "..", "..");
  const genPath = join(dirname(path), "..", "..", "gen");
  const mtimePath = join(
    genPath,
    `api.${name}.mtime.json`,
  );
  const apimetaPath = join(
    genPath,
    `api.${name}.meta.json`,
  );
  const apimeta = (await readAsync(apimetaPath, "json")) || {};
  if (!apimeta[name]) {
    apimeta[name] = {};
  }
  if (apimeta[name]) {
    if (apimeta[name]._url) _url = apimeta[name]._url;
    if (apimeta[name]._params) _params = apimeta[name]._params;
  }

  let mtime = ((await readAsync(mtimePath, "json")) || {}) as Record<
    string,
    number
  >;

  const relPath = path.substring(root.length + 1);

  const pendingRemove: Promise<any>[] = [];
  for (let file of await listAsync(join(dirname(path), "..", "..", "gen"))) {
    if (file.startsWith("api.")) {
      pendingRemove.push(removeAsync(join(genPath, file)));
    }
  }
  await Promise.all(pendingRemove);

  await findAsync(path, {
    recursive: true,
    files: true,
    directories: false,
    filter: async (file) => {
      if (file.absolutePath && file.absolutePath.endsWith(".ts")) {
        const s = await stat(file.absolutePath);
        const filePath = file.absolutePath.substring(path.length + 1);
        let shouldParse = mtime[filePath] !== s.mtimeMs;
        mtime[filePath] = s.mtimeMs;

        const apiName = file.name
          .substring(0, file.name.length - 3)
          .replace(/\W/gi, "_");

        index.push({
          name: apiName,
          path: `../${relPath}/` +
            file.absolutePath.substring(
              path.length + 1,
              file.absolutePath.length - 3,
            ),
        });

        if (file.size < 10) {
          await writeAsync(
            file.absolutePath,
            `\
  import { APIContext } from 'royal'
  
  export const _ = {
    url: '/${apiName}',
    async api(name: string) {
      const server: APIContext = this as any
  
      return { hello: name || "" }
    },
  }`,
          );
          shouldParse = true;
        }
        if (shouldParse || !_params[apiName] || !_url[apiName]) {
          const source = await readAsync(file.absolutePath, "utf8");

          if (source) {
            _params[apiName] = {
              api: [],
              url: [],
              service: [],
            };
            _url[apiName] = await new Promise<string>((resolve) => {
              const parsed = parse(source, {
                sourceType: "module",
                plugins: [[pluginTs]],
              });

              let url = "";
              traverse(parsed, {
                ObjectMethod: (p) => {
                  const c = p.node;
                  const params: string[] = [];
                  if (c.key.type === "Identifier" && c.key.name === "api") {
                    for (let [_, param] of Object.entries(c.params)) {
                      let name = "";
                      if (param.type === "Identifier") {
                        name = param.name;
                      }
                      params.push(name);
                    }
                  }
                  _params[apiName].api = params;
                },
                ObjectProperty: (p) => {
                  if (url) return;

                  const c = p.node;
                  if (c.key.type === "Identifier" && c.key.name === "url") {
                    if (c.value.type === "StringLiteral") {
                      url = c.value.value;
                      resolve(url);
                    }
                  }
                },
              });
            });

            _params[apiName].url = parseParameterizedPathname(_url[apiName]);

            for (let param of _params[apiName].url) {
              if (_params[apiName].api.includes(param)) {
                _params[apiName].service.push(param);
              }
            }
          }
        }
      }
      return true;
    },
  });

  apimeta[name] = { _url, _params };
  await writeAsync(apimetaPath, apimeta);
  await writeAsync(mtimePath, mtime);
  await writeAsync(
    join(dirname(path), "..", "..", "gen", `api.${name}.ts`),
    `\
  /** AUTOGENERATED - DO NOT EDIT **/
  export {};
  ${
      index
        .map((e) => {
          return `export { _ as ${e.name} } from "${e.path}"`;
        })
        .join("\n")
    }
    `,
  );
};

export const generateApiIndex = async (srvs: string[], path: string) => {
  await writeAsync(
    join(path, `api.ts`),
    `\
  /** AUTOGENERATED - DO NOT EDIT **/
  export {};
  ${
      srvs
        .map((e) => {
          return `export * as ${e} from "./api.${e}"`;
        })
        .join("\n")
    }
    `,
  );
};

const parseParameterizedPathname = (pathname: string) => {
  const params: Record<string, true> = {};
  const splited = pathname.split(":");

  for (let s of splited) {
    const idx = s.indexOf("/");
    if (idx) {
      params[s.substring(0, idx)] = true;
    }
  }
  return Object.keys(params);
};

function JSONstringifyOrder(obj: any, space: number) {
  const allKeys = new Set();
  JSON.stringify(obj, (key, value) => (allKeys.add(key), value));
  return JSON.stringify(obj, Array.from(allKeys).sort() as any, space);
}
