import { dirname, join } from "path";
import {
  dirAsync,
  findAsync,
  listAsync,
  readAsync,
  removeAsync,
  writeAsync,
} from "service";

import { stat } from "fs/promises";
import { ApiMetaParams } from "service";
import { InspectResult } from "service/internal/service/build/jetpack/types";
import swc from "@swc/core";
import Visitor from "../scaff/swc/visitor";

type MTime = Record<
  string,
  number
>;

type IndexEntry = { name: string; path: string };
type UrlMap = Record<string, string>;
export const scaffoldAPI = async (
  name: string,
  apiPath: string,
  changedPath?: string,
) => {
  await dirAsync(apiPath);
  const index = [] as IndexEntry[];

  let _url: UrlMap = {};
  let _params: ApiMetaParams = {};
  const root = join(dirname(apiPath), "..", "..");
  const genPath = join(dirname(apiPath), "..", "..", "gen");
  const mtimePath = join(
    genPath,
    `api.mtime.json`,
  );
  const apimetaPath = join(
    genPath,
    `api.meta.json`,
  );
  const apimeta = (await readAsync(apimetaPath, "json")) || {};
  if (!apimeta[name]) {
    apimeta[name] = {};
  }
  if (apimeta[name]) {
    if (apimeta[name]._url) _url = apimeta[name]._url;
    if (apimeta[name]._params) _params = apimeta[name]._params;
  }

  if (changedPath) {
    const changedName = changedPath
      .substring(0, changedPath.length - 3)
      .replace(/\W/gi, "_");

    delete _url[changedName];
    delete _params[changedName];
  } else {
    const pendingRemove: Promise<any>[] = [];
    const dirs = await listAsync(genPath);
    if (dirs) {
      for (let file of dirs) {
        if (file.startsWith("api.")) {
          pendingRemove.push(removeAsync(join(genPath, file)));
        }
      }
    }
    await Promise.all(pendingRemove);
  }

  let mtime = ((await readAsync(mtimePath, "json")) || {}) as MTime;

  const relPath = apiPath.substring(root.length + 1);

  const promises: Promise<void>[] = [];
  await findAsync(apiPath, {
    recursive: true,
    files: true,
    directories: false,
    filter: (file) => {
      promises.push(
        scanAPIMeta({ file, apiPath, mtime, index, relPath, _params, _url }),
      );
      return true;
    },
  });

  await Promise.all(promises);

  apimeta[name] = { _url, _params };

  await writeAsync(
    apimetaPath,
    JSON.stringify(apimeta, replacer, 2),
  );
  await writeAsync(
    mtimePath,
    JSON.stringify(mtime, replacer, 2),
  );
  await writeAsync(
    join(dirname(apiPath), "..", "..", "gen", `api.${name}.ts`),
    `\
/** AUTOGENERATED - DO NOT EDIT **/
export {};
${
      index
        .map((e) => {
          return `export { _ as ${e.name} } from "${e.path}"`;
        })
        .sort((a, b) => a.localeCompare(b))
        .join("\n")
    }
    `,
  );
};

export const generateApiIndex = async (srvs: string[], path: string) => {
  await writeAsync(
    join(path, `api.ts`),
    `\
  /** AUTOGENERATED - DO NOT EDIT **/
  export {};
  ${
      srvs
        .map((e) => {
          return `export * as ${e} from "./api.${e}"`;
        })
        .join("\n")
    }
    `,
  );
};

const parseParameterizedPathname = (pathname: string) => {
  const params: Record<string, true> = {};
  const splited = pathname.split(":");

  for (let s of splited) {
    const idx = s.indexOf("/");
    if (idx) {
      params[s.substring(0, idx)] = true;
    }
  }
  return Object.keys(params);
};

function replacer(key: any, value: any) {
  if (value == null || value.constructor != Object) {
    return value;
  }
  return Object.keys(value).sort().reduce((s, k) => {
    s[k] = value[k];
    return s;
  }, {});
}
const scanAPIMeta = async (
  { file, apiPath, mtime, index, relPath, _params, _url }: {
    file: InspectResult;
    apiPath: string;
    mtime: MTime;
    relPath: string;
    index: IndexEntry[];
    _url: UrlMap;
    _params: ApiMetaParams;
  },
) => {
  if (file.absolutePath && file.absolutePath.endsWith(".ts")) {
    const s = await stat(file.absolutePath);
    const filePath = file.absolutePath.substring(apiPath.length + 1);
    let shouldParse = mtime[filePath] !== s.mtimeMs;
    mtime[filePath] = s.mtimeMs;

    const apiName = file.name
      .substring(0, file.name.length - 3)
      .replace(/\W/gi, "_");

    index.push({
      name: apiName,
      path: `../${relPath}/` +
        file.absolutePath.substring(
          apiPath.length + 1,
          file.absolutePath.length - 3,
        ),
    });

    if (file.size < 10) {
      await writeAsync(
        file.absolutePath,
        `\
import { apiContext } from "royal";
export const _ = {
  url: "/${apiName}",
  async api(name: string) {
    const ctx = apiContext(this);
    return { hello: name || "" };
  },
};
`,
      );
      shouldParse = true;
    }
    if (shouldParse || !_params[apiName] || !_url[apiName]) {
      const source = await readAsync(file.absolutePath, "utf8");

      if (source) {
        _params[apiName] = {
          api: [],
          url: [],
          service: [],
        };
        _url[apiName] = await new Promise<string>(async (resolve) => {
          try {
            let url = "";
            class Traverse extends Visitor {
              visitObjectProperty(
                c: swc.SpreadElement | swc.Property,
              ): swc.SpreadElement | swc.Property {
                if (
                  c.type === "MethodProperty" &&
                  c.key.type === "Identifier" &&
                  c.key.value === "api"
                ) {
                  const params: string[] = [];

                  for (let [_, param] of Object.entries(c.params)) {
                    let name = "";
                    if (param.pat.type === "Identifier") {
                      name = param.pat.value;
                    }
                    params.push(name);
                  }
                  _params[apiName].api = params;
                } else if (!url) {
                  if (
                    c.type === "KeyValueProperty" &&
                    c.key.type === "Identifier" &&
                    c.key.value === "url"
                  ) {
                    if (c.value.type === "StringLiteral") {
                      url = c.value.value;
                      resolve(url);
                    }
                  }
                }

                return c;
              }
            }
            const parsed = await swc.parse(source, {
              syntax: "typescript",
              tsx: true,
            });
            new Traverse().visitModule(parsed);
          } catch (e) {
          }
        });

        _params[apiName].url = parseParameterizedPathname(_url[apiName]);

        for (let param of _params[apiName].url) {
          if (_params[apiName].api.includes(param)) {
            _params[apiName].service.push(param);
          }
        }
      }
    }
  }
};
