import { spawn, spawnSync } from "child_process";
import { join } from "path";
import { dirAsync, existsAsync, removeAsync } from "service";
import { runPnpm } from "service/internal/service/build/run-pnpm";
import { Transform } from "stream";
import { scaff } from "../scaff/util/scaff";

let lastRestart = new Date().getTime();

const main = (async () => {
  let shouldInstallDep = await scaff({
    "package.json": {
      "name": "gen",
      "version": "0.0.1",
      "main": "service.ts",
    },
    "service.ts": `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/
export type _names = "royal";
export const _path = {
  "royal": "pkgs/royal/index.ts",
};
export const _runtime = {
  "royal": "node"
};
`,
    "action.ts": `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/
export { action as royal } from "../pkgs/royal/action";
`,
  }, join(process.cwd(), "gen"));

  if (!await existsAsync(join(process.cwd(), "node_modules"))) {
    shouldInstallDep = true;
  }

  const args = process.argv.slice(2);

  if (args.includes("deploy")) {
    await removeAsync(join(process.cwd(), ".output", "app"));
    await removeAsync(join(process.cwd(), ".output", "deploy.zip"));
  }
  if (args.length === 0) {
    args.push("debug");
  }

  if (shouldInstallDep) {
    await installDep();
  }

  const appcwd = join(process.cwd(), ".output", "app");
  await dirAsync(appcwd);

  if (args.includes("genbase")) {
    spawnSync(
      /^win/.test(process.platform) ? "pnpm.cmd" : "pnpm",
      ["jiti", "./base/gen.ts"],
      { cwd: join(process.cwd(), "pkgs", "royal") },
    );
    return;
  }

  const start = () => {
    const res = spawn(
      "bun",
      [
        args.indexOf("prod") >= 0 ||
          args.indexOf("staging") >= 0 ||
          args.indexOf("build") >= 0
          ? ""
          : "--hot",
        "--silent",
        "--no-install",
        join(process.cwd(), "app", "app.ts"),
        "base",
        ...args,
      ].filter((e) => e),
      { stdio: "inherit", cwd: appcwd },
    );

    res.on("exit", (code) => {
      const time = new Date().getTime();
      if (time - lastRestart < 2000 && code !== 111) return;
      if (code === 222 || code === 55) {
        return;
      }
      start();
      lastRestart = time;
    });
  };

  start();
});

const installDep = () => {
  return new Promise<number>((resolve) => {
    console.log("Installing project dependency");

    runPnpm(["i"], process.cwd()).then(resolve);
  });
};

main();
