import { stat } from "fs/promises";
import { join, sep } from "path";
import { dirAsync, listAsync, readAsync, writeAsync } from "./build/jetpack";
type Services = Record<
  string,
  {
    safeName: string;
    name: string;
    path: string;
    runtime: "node" | "deno" | "bun";
  }
>;

export const generateMeta = async (cwd: string, subdir = ["app", "pkgs"]) => {
  await dirAsync(join(cwd, "gen"));
  let changed = false;
  const services: Services = {};
  for (const dir of subdir) {
    const currentDir = join(cwd, dir);
    const dirs = await listAsync(currentDir);
    if (dirs) {
      for (const item of dirs) {
        const s = await stat(join(currentDir, item));
        if (s.isDirectory()) {
          const indexPath = join(currentDir, item, "index.ts").replaceAll(
            sep,
            "/",
          );
          try {
            const indexSrc = await readAsync(indexPath) || "";
            const fline = indexSrc.substring(0, indexSrc.indexOf("\n"));
            const runtime = (fline.split(`#!/usr/bin/env`).pop()?.trim() ||
              "node") as any;
            if (indexSrc && indexSrc.includes("declareService")) {
              services[item] = {
                name: item,
                safeName: item.replaceAll(/\W/ig, "_"),
                runtime,
                path: indexPath.substring(cwd.length + 1),
              };
            }
          } catch (_) {
            // skip if indexPath is not found
          }
        }
      }
    }
  }

  const _names = Object.keys(services)
    .sort((a, b) => {
      return a.localeCompare(b);
    })
    .map((e) => `"${e}"`);
  const gensrc = `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/

export type _names = ${_names.length > 0 ? _names.join(" | ") : '""'}; 

export const _path = {
  ${
    Object.values(services)
      .sort((a, b) => {
        return a.name.localeCompare(b.name);
      })
      .map((e) => {
        return `"${e.name}": "${e.path}"`;
      })
      .join(",\n  ")
  }
}

export const _runtime = {
  ${
    Object.values(services)
      .sort((a, b) => {
        return a.name.localeCompare(b.name);
      })
      .map((e) => {
        return `"${e.name}": "${e.runtime}"`;
      })
      .join(",\n  ")
  }
}
`;
  const appGenPath = join(cwd, "gen", "service.ts");
  const gen = await readAsync(appGenPath);
  if (gen !== gensrc) {
    changed = true;
    await writeAsync(appGenPath, gensrc);
  }

  if (
    await genAction({
      cwd,
      services,
      suffix: "",
      outfile: "action.ts",
    })
  ) {
    changed = true;
  }

  return changed;
};

const genAction = async ({
  cwd,
  services,
  suffix,
  outfile,
}: {
  cwd: string;
  services: Services;
  suffix: string;
  outfile: string;
}) => {
  const gnodeFile = join(cwd, "gen", outfile);
  const gnode = `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/

${
    Object.values(services)
      .sort((a, b) => {
        return a.name.localeCompare(b.name);
      })
      .map((e) => {
        return `import { action as ${e.safeName} } from '../${
          e.path.replace(
            "index.ts",
            "action" + suffix,
          )
        }';`;
      })
      .join("\n")
  }

export default {
  ${
    Object.values(services)
      .sort((a, b) => {
        return a.name.localeCompare(b.name);
      })
      .map((e) => {
        return `"${e.name}": ${e.safeName}`;
      })
      .join(",\n  ")
  }
}
  
  `;
  const gnodeOld = await readAsync(gnodeFile);

  if (gnode !== gnodeOld) {
    await writeAsync(gnodeFile, gnode);
    return true;
  }
  return false;
};
