import { spawn, spawnSync } from "child_process";
import { join } from "path";
import { scaff } from "../../royal/scaff/util/scaff";
import { dirAsync, existsAsync, readAsync, removeAsync } from "../export";
import { buildApp } from "../internal/service/build/build-app";
import { resolveDeps } from "../internal/service/build/resolve-deps";
import { runPnpm } from "../internal/service/build/run-pnpm";
import { isEqual } from "./is-equal";

let lastRestart = new Date().getTime();

const main = (async () => {
  await removeAsync(join(process.cwd(), "gen"));
  let shouldInstallDep = false;
  await scaff({
    "api.meta.json": {},
    "prisma.ts": `export const prisma = {};`,
    "package.json": {
      "name": "gen",
      "version": "0.0.1",
      "main": "service.ts",
    },
    "service.ts": `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/
export type _names = "royal";
export const _path = {
  "royal": "pkgs/royal/index.ts",
};
export const _runtime = {
  "royal": "node"
};
`,
    "action.ts": `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/
export { action as royal } from "../pkgs/royal/action";
`,
  }, join(process.cwd(), "gen"));

  if (!await existsAsync(join(process.cwd(), "node_modules"))) {
    shouldInstallDep = true;
  }

  const args = process.argv.slice(2);

  if (args.includes("deploy")) {
    await removeAsync(join(process.cwd(), ".output", "deploy"));
    await removeAsync(join(process.cwd(), ".output", "deploy.zip"));
  }
  if (args.length === 0) {
    args.push("debug");
  }

  if (shouldInstallDep) {
    await installDep();
  }

  const appcwd = join(process.cwd(), ".output", "app");
  await dirAsync(appcwd);

  if (args.includes("genbase")) {
    spawnSync(
      process.execPath,
      ["-r", "jiti/register", "./base/gen.ts"],
      {
        stdio: "inherit",
        cwd: join(process.cwd(), "pkgs", "service"),
        env: {
          JITI_CACHE: join(process.cwd(), ".output", ".jiti"),
          JITI_ESM_RESOLVE: "1",
        },
      },
    );
    return;
  }

  const start = async () => {
    const pk1 = await readAsync(
      join(process.cwd(), ".output", "app", "package.json"),
      "json",
    );
    const ndeps = await resolveDeps(join(process.cwd(), "app"));

    await buildApp(join(process.cwd(), ".output", "app"));

    if (!pk1 || (pk1 && !isEqual(pk1.dependencies, ndeps))) {
      await runPnpm(["i"], join(process.cwd(), ".output", "app"));
    }
    const res = spawn(
      process.execPath,
      [
        "--enable-source-maps",
        "--no-warnings",
        join(process.cwd(), ".output", "app", "app.js"),
        "base",
        ...args,
      ].filter((e) => e),
      {
        stdio: "inherit",
        cwd: appcwd,
      },
    );

    res.on("exit", (code) => {
      const time = new Date().getTime();
      if (time - lastRestart < 2000 && code !== 111) return;
      if (code === 222 || code === 55) {
        return;
      }
      start();
      lastRestart = time;
    });
  };

  start();
});

const installDep = () => {
  return new Promise<number>((resolve) => {
    console.log("Installing project dependency");

    runPnpm(["i"], process.cwd()).then(resolve);
  });
};

main();
