import type { EditorThemeClasses } from "lexical";

import "./EditorTheme.css";

const theme: EditorThemeClasses = {
  blockCursor: "text_blockCursor",
  characterLimit: "text_characterLimit",
  code: "text_code",
  codeHighlight: {
    atrule: "text_tokenAttr",
    attr: "text_tokenAttr",
    boolean: "text_tokenProperty",
    builtin: "text_tokenSelector",
    cdata: "text_tokenComment",
    char: "text_tokenSelector",
    class: "text_tokenFunction",
    "class-name": "text_tokenFunction",
    comment: "text_tokenComment",
    constant: "text_tokenProperty",
    deleted: "text_tokenProperty",
    doctype: "text_tokenComment",
    entity: "text_tokenOperator",
    function: "text_tokenFunction",
    important: "text_tokenVariable",
    inserted: "text_tokenSelector",
    keyword: "text_tokenAttr",
    namespace: "text_tokenVariable",
    number: "text_tokenProperty",
    operator: "text_tokenOperator",
    prolog: "text_tokenComment",
    property: "text_tokenProperty",
    punctuation: "text_tokenPunctuation",
    regex: "text_tokenVariable",
    selector: "text_tokenSelector",
    string: "text_tokenSelector",
    symbol: "text_tokenProperty",
    tag: "text_tokenProperty",
    url: "text_tokenOperator",
    variable: "text_tokenVariable",
  },
  embedBlock: {
    base: "text_embedBlock",
    focus: "text_embedBlockFocus",
  },
  hashtag: "text_hashtag",
  heading: {
    h1: "text_h1",
    h2: "text_h2",
    h3: "text_h3",
    h4: "text_h4",
    h5: "text_h5",
    h6: "text_h6",
  },
  image: "editor-image",
  link: "text_link",
  list: {
    listitem: "text_listItem",
    listitemChecked: "text_listItemChecked",
    listitemUnchecked: "text_listItemUnchecked",
    nested: {
      listitem: "text_nestedListItem",
    },
    olDepth: ["text_ol1", "text_ol2", "text_ol3", "text_ol4", "text_ol5"],
    ul: "text_ul",
  },
  ltr: "text_ltr",
  mark: "text_mark",
  markOverlap: "text_markOverlap",
  paragraph: "text_paragraph",
  quote: "text_quote",
  rtl: "text_rtl",
  table: "text_table",
  tableAddColumns: "text_tableAddColumns",
  tableAddRows: "text_tableAddRows",
  tableCell: "text_tableCell",
  tableCellActionButton: "text_tableCellActionButton",
  tableCellActionButtonContainer: "text_tableCellActionButtonContainer",
  tableCellEditing: "text_tableCellEditing",
  tableCellHeader: "text_tableCellHeader",
  tableCellPrimarySelected: "text_tableCellPrimarySelected",
  tableCellResizer: "text_tableCellResizer",
  tableCellSelected: "text_tableCellSelected",
  tableCellSortedIndicator: "text_tableCellSortedIndicator",
  tableResizeRuler: "text_tableCellResizeRuler",
  tableSelected: "text_tableSelected",
  text: {
    bold: "text_textBold",
    code: "text_textCode",
    italic: "text_textItalic",
    strikethrough: "text_textStrikethrough",
    subscript: "text_textSubscript",
    superscript: "text_textSuperscript",
    underline: "text_textUnderline",
    underlineStrikethrough: "text_textUnderlineStrikethrough",
  },
};

export default theme;
