import { basename, join } from "path";
import { walkDir } from "../web/utils";
import { format } from "prettier";
import { writeAsync } from "service";

export const createWebLayout = async (path: string) => {
  const src = `\
import { layout } from 'web-init'
export default layout({
  component: ({ children }) => {
    return <>{children}</>
  },
})`;

  await writeAsync(path, src);
};

export const reloadWebLayout = async (basedir: string) => {
  const newLayouts: any = {};
  const list = await walkDir(basedir);

  for (let i of list) {
    const name = basename(
      i.endsWith(".tsx") ? i.substring(0, i.length - 4) : i,
    );
    newLayouts[name] = `() => import('../src/base/layout${
      i
        .substring(basedir.length, i.length - 4)
        .replace(/\\/gi, "/")
    }')`;
  }
  const output = `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/

export default {
${
    Object.entries(newLayouts)
      .map((arg: any) => {
        const [key, value] = arg;
        return `'${key}':${value},`;
      })
      .join("\n")
  }
}`;
  const formatted = format(output, { parser: "babel" });
  await writeAsync(
    join(basedir, "..", "..", "..", "types", "layout.ts"),
    formatted,
  );
};
