import { basename, join } from "path";
import { walkDir } from "../web/utils";
import { format } from "prettier";
import { listAsync, writeAsync } from "service";

export const createWebLayout = async (path: string) => {
  const src = `\
import { layout } from 'web-init'
export default layout({
  component: ({ children }) => {
    return <>{children}</>
  },
})`;

  await writeAsync(path, src);
};

export const reloadWebLayoutAll = async () => {
  const root = join(process.cwd(), "..", "..");
  const list = await listAsync(join(root, "app"));
  const layouts: any = {};
  if (list) {
    for (const svname of list) {
      if (svname.startsWith("web")) {
        layouts[svname] = {} as any;
        await reloadWebLayoutInternal(
          join(root, "app", svname),
          layouts[svname],
        );
      }
    }
  }

  const output = `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/

export default {
${
    Object.entries(layouts)
      .map((arg: any) => {
        const [key, value] = arg;
        return `'${key}':${value},`;
      })
      .join("\n")
  }
}`;
  const formatted = format(output, { parser: "babel" });
  await writeAsync(
    join(root, "gen", "web.layout.ts"),
    formatted,
  );
};

export const reloadWebLayoutSingle = async (
  webName: string,
) => {};

const reloadWebLayoutInternal = async (
  basedir: string,
  newLayouts: any,
) => {
  const list = await walkDir(basedir);

  for (let i of list) {
    const name = basename(
      i.endsWith(".tsx") ? i.substring(0, i.length - 4) : i,
    );
    newLayouts[name] = `() => import('../src/base/layout${
      i
        .substring(basedir.length, i.length - 4)
        .replace(/\\/gi, "/")
    }')`;
  }
};
