import { basename, join } from "path";
import { format } from "prettier";
import { listAsync, writeAsync } from "service";
import { walkDir } from "../web/utils";
import { parseWebPage } from "./parser/web-page-parser";

import { jsonReplacer } from "./util/stringify-replacer";

const pages: any = {};
const root = join(process.cwd(), "..", "..");

export const createWebPage = async (path: string) => {
  const name = basename(path).substring(0, basename(path).length - 4);
  const src = `\
import { page } from "types/content";
import { useLocal } from "web-utils";

export default page({
  url: "/${name}",
  component: ({}) => {
    return <div>Halo</div>;
  },
});
  `;

  await writeAsync(path, src);
};

export const reloadWebPageAll = async () => {
  const list = await listAsync(join(root, "app"));
  if (list) {
    for (const webName of list) {
      if (webName.startsWith("web")) {
        pages[webName] = {} as any;
        await reloadWebPageInternal(
          join(root, "app", webName, "src", "base", "page"),
          pages[webName],
        );
      }
    }
  }
  await writeWebPageInternal(root);
};

export const reloadWebPageSingle = async (
  webName: string,
) => {
  delete pages[webName];
  await reloadWebPageInternal(
    join(root, "app", webName),
    pages[webName],
  );
  await writeWebPageInternal(root);
};

const reloadWebPageInternal = async (
  basedir: string,
  curPage: any,
) => {
  const list = await walkDir(basedir);

  for (let path of list) {
    let pathNoExt = path.endsWith(".tsx")
      ? path.substring(0, path.length - 4)
      : path;

    const name = pathNoExt
      .substring(basedir.length + 1)
      .replace(/[\/\\]/gi, ".");

    let layout = "default";
    let url = "";

    await parseWebPage(path, ({ type, value }) => {
      if (type === "url" && !url) url = value;
      if (type === "layout") layout = value;
    });

    curPage[name] = `["${url}", "${layout}", () => import('..${
      path
        .substring(root.length, path.length - 4)
        .replace(/\\/gi, "/")
    }')]`;
  }
};

const writeWebPageInternal = async (root: string) => {
  const output = `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/

export default ${JSON.stringify(pages, jsonReplacer, 2)}`;

  const formatted = format(output, { parser: "babel" });
  await writeAsync(
    join(root, "gen", "web.layout.ts"),
    formatted,
  );
};
