import { basename, join } from "path";
import { format } from "prettier";
import { listAsync, writeAsync } from "service";
import { walkDir } from "../web/utils";

const layouts: any = {};
const root = join(process.cwd(), "..", "..");

export const createWebLayout = async (path: string) => {
  const src = `\
import { layout } from 'web-init'
export default layout({
  component: ({ children }) => {
    return <>{children}</>
  },
})`;

  await writeAsync(path, src);
};

export const reloadWebLayoutAll = async () => {
  const list = await listAsync(join(root, "app"));
  if (list) {
    for (const webName of list) {
      if (webName.startsWith("web")) {
        layouts[webName] = {} as any;
        await reloadWebLayoutInternal(
          webName,
          join(root, "app", webName, "src", "base", "layout"),
          layouts[webName],
        );
      }
    }
  }
  await writeWebLayoutInternal(root);
};

export const reloadWebLayoutSingle = async (
  webName: string,
) => {
  delete layouts[webName];
  layouts[webName] = {};
  await reloadWebLayoutInternal(
    webName,
    join(root, "app", webName, "src", "base", "layout"),
    layouts[webName],
  );
  await writeWebLayoutInternal(root);
};

const reloadWebLayoutInternal = async (
  webName: string,
  basedir: string,
  curLayout: any,
) => {
  const list = await walkDir(basedir);

  for (let i of list) {
    const name = basename(
      i.endsWith(".tsx") ? i.substring(0, i.length - 4) : i,
    );
    curLayout[name] = `() => import('../app/${webName}/src/base/layout${
      i
        .substring(basedir.length, i.length - 4)
        .replace(/\\/gi, "/")
    }')`;
  }
};

const writeWebLayoutInternal = async (root: string) => {
  const output = `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/

export default {
${
    Object.entries(layouts)
      .sort()
      .map((arg: any) => {
        const [key, value] = arg;
        return `'${key}':{${
          Object
            .entries(value).sort((a, b) =>
              a[0]
                .localeCompare(b[0])
            )
            .map(([k, v]) => {
              return `"${k}":${v}`;
            })
        }},`;
      })
      .join("\n")
  }
}`;

  const formatted = format(output, { parser: "babel" });
  await writeAsync(
    join(root, "gen", "web.layout.ts"),
    formatted,
  );
};
