import { basename, join } from "path";
import { format } from "prettier";
import { listAsync, writeAsync } from "service";
import { walkDir } from "../web/utils";
import { parseWebGen } from "./parser/web-gen-parser";

const gens: Record<string, Record<string, { path: string; src: string }>> = {};
const root = join(process.cwd(), "..", "..");

export const createWebGen = async (filepath: string) => {
  const src = `\
export const _ = async () => {
  return "";
};`;

  await writeAsync(filepath, src);
};

export const reloadWebGenAll = async () => {
  const list = await listAsync(join(root, "app"));
  if (list) {
    for (const webName of list) {
      if (webName.startsWith("web")) {
        gens[webName] = {} as any;
        await reloadWebGenInternal(
          webName,
          join(root, "app", webName, "src", "gen"),
          gens[webName],
        );
      }
    }
  }
  await writeWebGenInternal(root);
};

export const reloadWebGenSingle = async (webName: string) => {
  delete gens[webName];
  gens[webName] = {};
  await reloadWebGenInternal(
    webName,
    join(root, "app", webName, "src", "gen"),
    gens[webName],
  );
  await writeWebGenInternal(root);
};

const reloadWebGenInternal = async (
  webName: string,
  basedir: string,
  curGen: any,
) => {
  const list = await walkDir(basedir);

  for (let i of list) {
    const name = basename(
      i.endsWith(".ts") ? i.substring(0, i.length - 3) : i,
    );

    const paramsCount = await parseWebGen(i);

    const genExtend = (name: string, count: number, current = 0) => {
      if (count === current) return "any";

      return `\
{
  [k in Parameters<typeof ${name}>[${current}]]: ${
        genExtend(name, count, current + 1)
      };
}`;
    };

    curGen[name] = {
      path: i.substring(root.length),
      src: `\
extendGen({} as ${genExtend(`${webName}_${name}`, paramsCount)})`,
    };
  }
};

const writeWebGenInternal = async (root: string) => {
  const output = `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/
import { extendGen } from "../pkgs/royal/web/gen";
${
    Object.entries(gens)
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([k, obj]) => {
        return Object.entries(obj)
          .sort((a, b) => a[0].localeCompare(b[0]))
          .map(([name, item]) => {
            return `import { _ as ${k}_${name} } from "..${
              item.path.substring(0, item.path.length - 3)
            }"`;
          }).join("\n");
      })
  }

export default {
${
    Object.entries(gens)
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map((arg) => {
        const [key, value] = arg;
        return `'${key}':{${
          Object
            .entries(value).sort((a, b) =>
              a[0]
                .localeCompare(b[0])
            )
            .map(([k, v]) => {
              return `"${k}":${v.src}`;
            })
        }},`;
      })
      .join("\n")
  }
}`;

  const formatted = format(output, { parser: "typescript" });

  await writeAsync(
    join(root, "gen", "web.gen.ts"),
    formatted,
  );
};
