import { watch } from "chokidar";
import { writeFile } from "fs/promises";
import { basename, join } from "path";
import { format } from "prettier";
import { existsAsync } from "service";
import { g } from "../global";
import { getWebDirs, walkDir } from "../web/utils";

export const webWatcherLayout = async () => {
  for (const [name, dir] of Object.entries(await getWebDirs())) {
    const dirPath = join(dir, "src", "base", "layout");
    if (await existsAsync(dirPath)) {
      g.watchers.push(
        watch(dirPath, { ignoreInitial: true }).on(
          "all",
          (event, path) => reloadLayout.bind(name)(event, dir),
        ),
      );
      reloadLayout.bind(name)("init", dir);
    }
  }
};

const clientDir = (name: string, cdir: string) => ({
  root: join(cdir),
  layout: join(cdir, "src", "base", "layout"),
  layoutOut: join(cdir, "types", "layout.ts"),
});

async function reloadLayout(web: string, cdir: string) {
  const newLayouts: any = {};
  const list = await walkDir(clientDir(web, cdir).layout);

  for (let i of list) {
    const name = basename(
      i.endsWith(".tsx") ? i.substring(0, i.length - 4) : i,
    );
    newLayouts[name] = `() => import('..${
      i
        .substring(clientDir(web, cdir).root.length, i.length - 4)
        .replace(/\\/gi, "/")
    }')`;
  }
  const output = `\
/******************************************************/
/************* autogenerated - do not edit ************/
/******************************************************/

export default {
${
    Object.entries(newLayouts)
      .map((arg: any) => {
        const [key, value] = arg;
        return `'${key}':${value},`;
      })
      .join("\n")
  }
}`;
  const formatted = format(output, { parser: "babel" });
  await writeFile(clientDir(web, cdir).layoutOut, formatted);
}
